{
 "title": "MiniEngine - Rendering",
 "time": { "from": "now-1m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "pipeline",
    "query": "render_pipeline_stages_render_time,lighting_pipeline_stages_render_time,model_pipeline_stages_render_time,particle_pipeline_stages_render_time,shadow_pipeline_stages_render_time"
   }
  ]
 },
 "panels": [
  {
   "title": "$pipeline",
   "type": "graph",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 0 },
   "repeat": "pipeline",
   "yaxes": [
    { "format": "short", "label": "Milliseconds" }
   ],
   "targets": [
    {
     "expr": "max($pipeline * 1000) by (stage)",
     "legendFormat": "{{stage}}"
    },
    { "expr": "sum($pipeline * 1000)", "legendFormat": "Total" }
   ]
  },
  {
   "title": "$pipeline",
   "type": "graph",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short", "label": "Milliseconds" }
   ],
   "targets": [
    {
     "expr": "max($pipeline * 1000) by (stage)",
     "legendFormat": "{{stage}}"
    },
    { "expr": "sum($pipeline * 1000)", "legendFormat": "Total" }
   ]
  },
  {
   "title": "$pipeline",
   "type": "graph",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short", "label": "Milliseconds" }
   ],
   "targets": [
    {
     "expr": "max($pipeline * 1000) by (stage)",
     "legendFormat": "{{stage}}"
    },
    { "expr": "sum($pipeline * 1000)", "legendFormat": "Total" }
   ]
  },
  {
   "title": "$pipeline",
   "type": "graph",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "short", "label": "Milliseconds" }
   ],
   "targets": [
    {
     "expr": "max($pipeline * 1000) by (stage)",
     "legendFormat": "{{stage}}"
    },
    { "expr": "sum($pipeline * 1000)", "legendFormat": "Total" }
   ]
  },
  {
   "title": "$pipeline",
   "type": "graph",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "short", "label": "Milliseconds" }
   ],
   "targets": [
    {
     "expr": "max($pipeline * 1000) by (stage)",
     "legendFormat": "{{stage}}"
    },
    { "expr": "sum($pipeline * 1000)", "legendFormat": "Total" }
   ]
  },
  {
   "title": "ShadowMapSystem",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 65 },
   "yaxes": [
    { "format": "short", "label": "Milliseconds" }
   ],
   "targets": [
    {
     "expr": "max(shadow_pipeline_shadow_map_counter)",
     "legendFormat": "Total shadow map"
    },
    {
     "expr": "max(shadow_pipeline_shadow_map_cascades_counter)",
     "legendFormat": "Total shadow map cascades"
    },
    {
     "expr": "max(shadow_pipeline_total_render_time * 1000)",
     "legendFormat": "Total"
    },
    {
     "expr": "max(shadow_pipeline_step_render_time * 1000) by (step)",
     "legendFormat": "{{step}}"
    }
   ]
  },
  {
   "title": "RenderPipeline :: Histogram",
   "type": "graph",
   "gridPos": { "h": 6, "w": 23, "x": 1, "y": 77 },
   "yaxes": [
    { "format": "short", "label": "Milliseconds" }
   ],
   "targets": [
    {
     "expr": "max(render_pipeline_stages_render_time * 1000) by (stage)",
     "legendFormat": "{{stage}}"
    },
    {
     "expr": "sum(render_pipeline_stages_render_time * 1000)",
     "legendFormat": "Total"
    }
   ]
  }
 ]
}